name = "Atomsk"
uuid = "b5ea28c8-8fde-43cb-ab2a-66614f5bd9e2"
authors = ["Jason Meziere"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
